<?php
  if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
      'key'    => 'content_parts_group',
      'title'  => 'Inhaltsbereiche',
      'fields' => array(
        array(
          'key'   => 'field_589de719e917d',
          'label' => 'Abschnitte',
          'name'  => 'content_parts',
          'type'  => 'flexible_content',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id'    => '',
          ),
          'layouts' => array(
            '589de729a0da7' => array(
              'key' => '589de729a0da7',
              'name' => 'text',
              'label' => 'Textblock',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_589de856e917e',
                  'label' => 'Inhalt',
                  'name' => 'content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '591d48b653860' => array(
              'key' => '591d48b653860',
              'name' => 'columns',
              'label' => 'Spalten',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_591d490753867',
                  'label' => 'Spalteninhalt',
                  'name' => 'columns',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 2,
                  'max' => 4,
                  'layout' => 'block',
                  'button_label' => 'Spalte hinzufügen',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_591d4c0953869',
                      'label' => 'Spalten-Typ',
                      'name' => 'column_type',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'text' => 'Text',
                        'image' => 'Bild',
                        'button' => 'Button',
                      ),
                      'default_value' => array(),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'return_format' => 'value',
                      'ajax' => 0,
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5c90d46723cd1',
                      'label' => 'Vertikale Ausrichtung',
                      'name' => 'vertical_align',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'top' => 'Obere Abschnittsgrenze',
                        'center' => 'Zentriert',
                        'bottom' => 'Untere Abschnittsgrenze',
                      ),
                      'default_value' => array(),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'return_format' => 'value',
                      'show_column' => 0,
                      'show_column_sortable' => 0,
                      'show_column_weight' => 1000,
                      'allow_quickedit' => 0,
                      'allow_bulkedit' => 0,
                      'ajax' => 0,
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_591d48b753861',
                      'label' => 'Text',
                      'name' => 'column_text',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => array(
                        array(
                          array(
                            'field' => 'field_591d4c0953869',
                            'operator' => '==',
                            'value' => 'text',
                          ),
                        ),
                      ),
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 0,
                      'delay' => 0,
                    ),
                    array(
                      'key' => 'field_591d4c3e5386a',
                      'label' => 'Bild',
                      'name' => 'column_img',
                      'type' => 'image',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => array(
                        array(
                          array(
                            'field' => 'field_591d4c0953869',
                            'operator' => '==',
                            'value' => 'image',
                          ),
                        ),
                      ),
                      'wrapper' => array(
                        'width' => 60,
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                      'preview_size' => 'medium',
                      'library' => 'all',
                      'min_width' => 480,
                      'min_height' => 360,
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => 'jpg,png,jpeg',
                    ),
                    array(
                      'key' => 'field_5d5fdeb5ea8b2',
                      'label' => 'Button',
                      'name' => 'button-content',
                      'type' => 'link',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => array(
                        array(
                          array(
                            'field' => 'field_591d4c0953869',
                            'operator' => '==',
                            'value' => 'button',
                          ),
                        ),
                      ),
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '58aef8395313b' => array(
              'key' => '58aef8395313b',
              'name' => 'tabs',
              'label' => 'Tab Element',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_58aefc975313e',
                  'label' => 'Tab Elemente',
                  'name' => 'tabs',
                  'type' => 'repeater',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => 'field_58aef84c5313c',
                  'min' => 2,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => 'Tab hinzufügen',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_58aef84c5313c',
                      'label' => 'Titel',
                      'name' => 'tab_title',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => '',
                      'conditional_logic' => '',
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array(
                      'key' => 'field_58aefc7b5313d',
                      'label' => 'Textfeld',
                      'name' => 'tab_text',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 1,
                      'delay' => 1,
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            '58aefcea5313f' => array(
              'key'        => '58aefcea5313f',
              'name'       => 'accordion',
              'label'      => 'Akkordeon Element',
              'display'    => 'block',
              'sub_fields' => array(
                array(
                  'key'               => 'field_58aefcea53140',
                  'label'             => 'Akkordeon Elemente',
                  'name'              => 'accordion',
                  'type'              => 'repeater',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => array(
                    'width'           => '',
                    'class'           => '',
                    'id'              => '',
                  ),
                  'collapsed'         => 'field_58aefcea53141',
                  'min'               => 2,
                  'max'               => 0,
                  'layout'            => 'row',
                  'button_label'      => 'Element hinzufügen',
                  'sub_fields'        => array(
                    array(
                      'key'          => 'field_58aefcea53141',
                      'label'        => 'Titel',
                      'name'         => 'accordion_title',
                      'type'         => 'text',
                      'instructions' => '',
                      'required'     => 1,
                      'conditional_logic' => 0,
                      'wrapper'      => array(
                        'width'      => '',
                        'class'      => '',
                        'id'         => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                      'readonly' => 0,
                      'disabled' => 0,
                    ),
                    array(
                      'key' => 'field_58aefcea53142',
                      'label' => 'Textfeld',
                      'name' => 'accordion_text',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 1,
                      'delay' => 1,
                    ),
                    array(
                      'key' => 'field_595a19399f353',
                      'label' => 'Headerbild / Slider',
                      'name' => 'accordion_image',
                      'type' => 'gallery',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'min' => '',
                      'max' => '',
                      'insert' => 'append',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                      'show_column' => 0,
                      'show_column_weight' => 1000,
                      'return_format' => 'array',
                      'preview_size' => 'medium',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5b6d8485c2f1f' => array(
              'key' => 'layout_5b6d8485c2f1f',
              'name' => 'gallery',
              'label' => 'Galerie',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b6d848ec2f20',
                  'label' => 'Bilder',
                  'name' => 'images',
                  'type' => 'gallery',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'min' => 2,
                  'max' => '',
                  'insert' => 'append',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                  'show_column' => 0,
                  'show_column_weight' => 1000,
                  'return_format' => 'array',
                  'preview_size' => 'medium',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5b71a05bb80c4' => array(
              'key' => 'layout_5b71a05bb80c4',
              'name' => 'news',
              'label' => 'News / Aktuelles',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5b71a05bb80c5',
                  'label' => 'Kategorie Auswahl',
                  'name' => 'news-category',
                  'type' => 'taxonomy',
                  'instructions' => 'Wenn keine Kategorie ausgewählt wird, werden die aktuellsten News ausgegeben.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'taxonomy' => 'category',
                  'field_type' => 'checkbox',
                  'add_term' => 0,
                  'save_terms' => 0,
                  'load_terms' => 0,
                  'return_format' => '',
                  'show_column' => 0,
                  'show_column_weight' => 1000,
                  'allow_quickedit' => 0,
                  'allow_bulkedit' => 0,
                  'multiple' => 0,
                  'allow_null' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5c90d55f23cd2' => array(
              'key' => 'layout_5c90d55f23cd2',
              'name' => 'downloads',
              'label' => 'Downloads',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c93959fc6304',
                  'label' => 'Headline',
                  'name' => 'download-headline',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => 2,
                  'new_lines' => '',
                  'show_column' => 0,
                  'show_column_weight' => 1000,
                  'allow_quickedit' => 0,
                  'allow_bulkedit' => 0,
                ),
                array(
                  'key' => 'field_5c90d55f23cd3',
                  'label' => 'Kategorie Auswahl',
                  'name' => 'download-category',
                  'type' => 'taxonomy',
                  'instructions' => 'Wenn keine Kategorie ausgewählt wird, werden alle Downloads ausgegeben.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'taxonomy' => 'download_tax',
                  'field_type' => 'checkbox',
                  'add_term' => 0,
                  'save_terms' => 0,
                  'load_terms' => 0,
                  'return_format' => 'id',
                  'show_column' => 0,
                  'show_column_weight' => 1000,
                  'allow_quickedit' => 0,
                  'allow_bulkedit' => 0,
                  'multiple' => 0,
                  'allow_null' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5c90e3aa72bc8' => array(
              'key' => 'layout_5c90e3aa72bc8',
              'name' => 'opening-hours',
              'label' => 'Öffnungszeiten',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5c90e3aa72bc9',
                  'label' => 'Öffnungszeiten',
                  'name' => '',
                  'type' => 'message',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'message' => 'Es werden automatisch die Öffnungszeiten wie in den <a href="admin.php?page=acf-options-oeffnungszeiten">Einstellungen</a> (unter Allgemein -> Öffnungszeiten) hinterlegt, ausgegeben.',
                  'new_lines' => 'wpautop',
                  'esc_html' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5d5fd29bea8b0' => array(
              'key' => 'layout_5d5fd29bea8b0',
              'name' => 'button',
              'label' => 'Button',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5d5fd2a1ea8b1',
                  'label' => 'Button',
                  'name' => 'button-content',
                  'type' => 'link',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'subpages_layout' => array(
              'key' => 'subpages_layout',
              'name' => 'subpages',
              'label' => 'Unterseiten',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'subpage_info',
                  'label' => 'Unterseiten',
                  'name' => '',
                  'type' => 'message',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'message' => 'Es werden automatisch die Unterseiten in einer Kachelansicht ausgegeben.',
                  'new_lines' => 'wpautop',
                  'esc_html' => 0,
                )
              ),
              'min' => '',
              'max' => '',
            ),
            'image_list_layout' => array(
              'key'     => 'image_list_layout',
              'name'    => 'image_list',
              'label'   => 'Bilder Liste',
              'display' => 'block',
              'sub_fields' => array(
                array(
                  'key'               => 'list_images',
                  'label'             => 'Bilder',
                  'name'              => 'list_images',
                  'type'              => 'repeater',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'collapsed' => '',
                  'min' => 2,
                  'max' => 4,
                  'layout' => 'block',
                  'button_label' => 'Element hinzufügen',
                  'sub_fields'   => array(
                    array(
                      'key'          => 'field_591d4c3e5386a',
                      'label'        => 'Bild',
                      'name'         => 'column_img',
                      'type'         => 'image',
                      'instructions' => '',
                      'required'     => 1,
                      'wrapper' => array(
                        'width' => 25,
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                      'preview_size'  => 'medium',
                      'library'       => 'all',
                      'min_width'     => 240,
                      'min_height'    => 240,
                      'min_size'      => '',
                      'max_width'     => '',
                      'max_height'    => '',
                      'max_size'      => '',
                      'mime_types'    => 'jpg,png,jpeg',
                    ),
                    array(
                      'key'   => 'liste_image_text_field',
                      'label' => 'Text',
                      'name'  => 'image_text_field',
                      'type'  => 'wysiwyg',
                      'instructions' => '',
                      'required' => 1,
                      'wrapper' => array(
                        'width' => '75',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 0,
                      'delay' => 0,
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Abschnitt hinzufügen',
          'min' => '',
          'max' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'page',
          ),
          array(
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'default',
          ),
          array(
            'param' => 'page_type',
            'operator' => '!=',
            'value' => 'front_page',
          ),
        ),
      ),
      'menu_order' => 16,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => array(),
      'active' => true,
      'description' => '',
    ));

  } //endif